### ISSUE TITLE
Material Editor issue

### ISSUE THREAD

**Issue by SpaceMarine4040** [DaintyIL/Illusion_Deformers#1]
Having 2 squeezer accessories that have both been set to "Clothes True" causes neither to work. With one squeezer accessory set to "Clothes True" it works just fine, but on changing a second via the material editor or copying the accessory it stops working. Not sure if it is due to something on my end such as the version of material editor and other mods involved.

Overall a fantastic job, but his is something I noticed with a clear cause that it might help you to know about.

**Comment by DaintyIL** [comment]
Appreciate the report, helps a lot.

Could you please let me know if v0.21 fixes these issues for you?
https://github.com/DaintyIL/Illusion_Deformers/releases/tag/v0.21

**Comment by SpaceMarine4040** [comment]
that did the trick, having two set to that mode no longer causes them to stop working
