### ISSUE TITLE
The deformer mod can sometimes affect the texture and color of other accessories

### ISSUE THREAD

**Issue by uuupuuu** [DaintyIL/Illusion_Deformers#2]
![image](https://user-images.githubusercontent.com/81008314/111862833-1257e200-8915-11eb-8be2-8f176d49ccd1.png)
as shown in the pic, this accessory show some black edges after adding four deformers.
Additional note: This issue has nothing to do with the overlapping of deformers and affected accessories. For the case in the pic, the deformers are positioned at foot and the affected accessories are on the head so they don't overlap.

**Comment by DaintyIL** [comment]
Thanks for the report. There was an issue with recalculating normals for very small meshes. It should be fixed with the last commit/next release.
