### ISSUE TITLE
Deformers affecting half off state of some pantyhose.

### ISSUE THREAD

**Issue by DirtyDarkling** [DaintyIL/Illusion_Deformers#3]
Deformers.dll is affecting the half off state of some pantyhose, even when no deformer accessories are actually used on a character. Simply having the DLL in the plugins folder will cause the issue.  It seems to be any pantyhose that use the pulled down half off state rather than the vanilla way.
![HS2_2021-04-03-15-07-58-985b](https://user-images.githubusercontent.com/64672234/113489090-139a1a80-9490-11eb-8e2e-39a95a6c064b.png)
With deformers.dll disabled
![HS2_2021-04-03-15-10-25-372b](https://user-images.githubusercontent.com/64672234/113489094-16950b00-9490-11eb-9ec4-b05490008114.png)
With deformers.dll enabled
![HS2_2021-04-03-15-08-13-602b](https://user-images.githubusercontent.com/64672234/113489096-18f76500-9490-11eb-9391-dad3974cc592.png)
The scene file if you'd like to test.
![2021_0403_1507_33_472](https://user-images.githubusercontent.com/64672234/113489236-15181280-9491-11eb-99dd-d95c5823abe8.png)

**Comment by DaintyIL** [comment]
This is the cloth component issue that I thought was fixed with v0.31, just a special case I hadn't considered. Should be fixed with the next release. 
Thanks for the scene, that helped tracking it down.
