### ISSUE TITLE
Need Illusion Developer

### ISSUE THREAD

**Issue by artisansofpathos** [DaintyIL/Illusion_Deformers#4]
Can you help my friends and I with developing a plugin that works with Honey Select 2? If so, please reach out at our Discord, https://discord.gg/gryYvNEf  or email us at   artisansofpathos@gmail.com

**Comment by artisansofpathos** [comment]
Very sorry to reach out here.

**Comment by DaintyIL** [comment]
The Illusion and Koikatsu discords both have development channels, you should ask there.
